### ISSUE TITLE
Knomi 2 container issues

### ISSUE THREAD

**Issue by lindnjoe** [DraftShift/ModularDock#12]
When you slice the knomi 2 container, it looses some of the outer walls.

**Comment by TheSin-** [comment]
that seems to be more of a slicer issue, enable thin walls?

**Comment by lindnjoe** [comment]
I got it to work, had to switch to a .2 nozzle and then it would slice without the missing walls. .4 nozzle and it would leave out the side walls.

**Comment by TheSin-** [comment]
odd I run .4 and have no issues, still feel it's a slicer issue.

Glad you go it.

**Comment by testack18** [comment]
For others who are running into the same issue. I had this as well. My slicer base profile is from Ellis's profile where the thin wall min with is 33%: thin_walls_min_width = 33% (SS profile setting)
I had to decrease this to 15% - 16% then the side thin walls were sliced correctly.
As this is a % value, the minimum may varies depends on your perimeter width settings. Check your G-Code preview before hit print.
I hope this helps other.
