### ISSUE TITLE
Will there also be a RapidBurner Dock version?

### ISSUE THREAD

**Issue by orotecluc** [DraftShift/ModularDock#5]
Hi,
Congratz on your project, looks really great.
Only thing : I am not into 3D drawing, and am using RapidBurner toolheads (with G2SA extruders) and woul love to use your DoorSHift / Modular Dock to be able to have a toolchanging mechanism...
I currently have my toolheads printed with the Rapid Cowl as provided by Viesturz  [https://github.com/viesturz/tapchanger/tree/main/Tapchanger/STL/Toolheads/RapidBurner](https://github.com/viesturz/tapchanger/tree/main/Tapchanger/STL/Toolheads/RapidBurner)

**Comment by TheSin-** [comment]
I'm hoping to add one, the issue with the taller tools is mixing, I'm working on that though.

Technically the DB dock should work with it though.

**Comment by TheSin-** [comment]
Added with https://github.com/DraftShift/ModularDock/commit/2ed60977f21839fce415b70efb9c046ddea14223
